### ISSUE TITLE
Won't work with some other libraries

### ISSUE THREAD

**Issue by mark-summerfield** [fireeye/cWMI#1]
I've written a small Python app which uses cwmi and this works fine.

However, when I try to use it in a Python 3/PySide1 app I get this error:
```unexpected OSError error: [WinError -2147417850] Cannot change thread mode after it is set.```

Also, it would be nice if it were pip-installable and on PyPI.

**Comment by abergl** [comment]
Do you have a full stack trace? If so, please post it.

**Comment by abergl** [comment]
Are you using the WMI class directly? If so, try setting the `coinit` parameter. This may resolve the issue.

**Comment by mark-summerfield** [comment]
I'm sorry, but I've now switched to another solution and am no longer able to reproduce the problem.
